#!/bin/bash

set -e

# Move to project root
SCRIPT_PATH=$(dirname `which $0`)
cd $SCRIPT_PATH/../

# Make sure all deps are installed
echo "Installing CI requirements first"
python -m pip install -r .ci/requirements.txt
echo "Installing regular requirements"
python -m pip install -r requirements.txt

# Run linting and tests
flake8 app/
pytest
