name: Master CICD Pipeline

on:
  push:
    branches: main

jobs:

  build:
    name: Continuous Integration of the endpoint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Display something useless
      run: |
        echo "Hello World automated from the master pipeline !"

    - name: Build the docker image with the registry name in it
      run: |
        git_hash=$(git rev-parse --short HEAD)
        docker build . -t docker.pkg.github.com/robbertDM/exercise-7-ci/project-api:$git_hash
